name: Unit and Integration Tests with Full Report

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests and generate coverage report
        run: npm test -- --coverage --coverageReporters=lcov

      - name: Parse LCOV file for per-file coverage
        id: parse_lcov
        run: |
          echo "### Coverage Summary by File" > coverage_summary.md
          echo "| File | Statements | Branches |" >> coverage_summary.md
          echo "|------|------------|----------|" >> coverage_summary.md
          awk '/SF:/ {file=$0} /DA:/ {statements++} /BRDA:/ {branches++} /BRDA:.*0$/ {uncovered_branches++} \
              END {print file, statements, uncovered_branches}' coverage/lcov.info | while read file statements uncovered_branches; do
            statement_coverage=$((100 - (uncovered_branches * 100 / statements)))
            echo "| ${file} | ${statement_coverage}% | ${uncovered_branches}% |" >> coverage_summary.md
          done

      - name: Post coverage summary as PR comment
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_BODY=$(cat coverage_summary.md)
          PR_NUMBER="${{ github.event.pull_request.number }}"
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"body\": \"$COMMENT_BODY\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
